### ISSUE TITLE
Chinese Localization SIG onboarding checklist

### ISSUE THREAD

**Issue by LinuxSuRen** [cdfoundation/toc#102]
This is the checklist for Chinese Localization SIG

* [ ] Create GitHub repo
* [ ] Create GitHub team for the SIG (cochairs should manage the team)
* [ ] Create slack channel (or rename existing channel to reflect sig name)
* [ ] Create groups.io mailing list
* [ ] SIG co-chairs to get access to CDF calendar to modify events
* [ ] Create SIG playlist on Youtube
* [ ] Announcement blog post/press release
* [ ] Recommend scheduling a podcast: https://cd.foundation/podcast/

**Comment by fdegir** [comment]
I believe foundation staff have permission for these tasks so it would be good to create an issue in https://github.com/cdfoundation/foundation/issues.

/cc @tracymiranda

**Comment by LinuxSuRen** [comment]
hi @fdegir thanks for your response.

**Comment by tracymiranda** [comment]
Repo & github team created, https://github.com/cdfoundation/sig-chinese-localization

Request for mailing list in progress

**Comment by tracymiranda** [comment]
Gale has created the list. Here is the link to the list - https://lists.cd.foundation/g/sig-chinese-localization

**Comment by LinuxSuRen** [comment]
hi @tracymiranda , do you know who can help us to have access to Youtube and Zoom accounts? Thanks!

**Comment by oleg-nenashev** [comment]
Gentle ping @tracymiranda

**Comment by oleg-nenashev** [comment]
I also added it to the CDF TOC agenda
