### ISSUE TITLE
Joining the Inclusive Naming Initiative

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#108]
I would like to formally follow-up on a proposal for the Continuous Delivery Foundation to join the Inclusive Naming Initiative (INI) as a member organization.The goal of this initiative is to help projects and companies make consistent, responsible choices to remove harmful language. It was started by several community leaders from the Cloud Native Computing Foundation, and there .

- Thread in the mailing list with full proposal: https://lists.cd.foundation/g/cdf-toc/topic/84333824#725
- Website: https://inclusivenaming.org/

Status:

- [x] TOC approval
- [x] Request to the Inclusive Naming Initiative
- [x] Inclusive Naming Initiative approval
- [x] Inclusive Naming Initiative website update
- [ ] CDF website update
- [ ] Public Announcement

**Comment by sbtaylor15** [comment]
@oleg-nenashev should each project have a Inclusivity Statement like the Code Of Conduct?

**Comment by tracymiranda** [comment]
No update to the application proposal as of today.

**Comment by bradmccoydev** [comment]
I just checked this and looks like CDF is on their website now so looks like we can tick off the boxes for approval and their website update, this is great news! you can see here with it on the site: https://inclusivenaming.org/ I'm happy to help with the blog post on this

**Comment by bradmccoydev** [comment]
Hey, @zestyroxy I'm happy to work with you on this I will reach out to you on slack.

**Comment by zestyroxy** [comment]
Sounds great @bradmccoydev. If you can create a Gdoc with the main points, we can collaborate there.

**Comment by oleg-nenashev** [comment]
But yeah, @bradmccoydev is right. Since they formally added the CDF, I think we could assume the enrollment is completed. I received no communication from the INI/LF as far as I can tell, but it should not block us. The membership still has some community and marketing value

**Comment by afrittoli** [comment]
Thanks @oleg-nenashev for the clarification

**Comment by afrittoli** [comment]
The CDF is marked as "associate sponsor" on the initiative website https://inclusivenaming.org/
