### ISSUE TITLE
Streamline/simplify project onboarding

### ISSUE THREAD

**Issue by oleg-nenashev** [cdfoundation/toc#116]
As we discovered there is conflicting information in the TOC documentation, including the requirements to the incubating projects and the onboarding flow. It would be great to clean up the documentation so that the project could easily follow the onboarding pipeline.

Related issues

- [x] Remove non-existent sandbox state #98 
- [x] Remove duplication - #109
- [ ] Create new application template for incubating #115 
- [ ] Create a new “How to join the CDF?” guide
