### ISSUE TITLE
TOC Sustainability

### ISSUE THREAD

**Issue by afrittoli** [cdfoundation/toc#178]
```[tasklist]

### Tasks
- [ ] https://github.com/cdfoundation/toc/issues/194
- [ ] https://github.com/cdfoundation/toc/issues/195
- [ ] https://github.com/cdfoundation/toc/issues/196
```
